apiVersion: apps/v1
kind: Deployment
{{- /*GO comment , trims white space after -  */}}
{{/*GO comment , trims white space before -  */ -}}
metadata:
{{- /* . = current context, top level  */}}
  name: {{ .Chart.Name }}
  labels:
    app: nginx
{{/*  white space  */}}
spec:
  {{- if eq .Values.environment "prod" }}
  replicas: {{ .Values.replicaCount }}
  {{- else }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    {{/*  function <arg1> <arg2>  with PIPE => result is passed to second fnction as arg  */}}
    matchLabels:
      app: {{ replace " " "-" .Chart.Name | lower  }}
  template:
    metadata:
      labels:
        app: nginx #same as matchLabels.app
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort.http }}