apiVersion: apps/v1
kind: Deployment
{{- /*GO comment , trims white space after -  */}}
{{/*GO comment , trims white space before -  */ -}}
metadata:
{{- /* . = current context, top level  */}}
{{- /* Release => unique namespace - set in command helm install local-nginx */}}
  name: {{ .Release.Name }}-{{ .Chart.Name}} #local-nginx-nginx
  labels:
    app: {{ .Chart.Name}}
    release: {{ .Release.Name }}
{{/*  white space  */}}
spec:
  {{- if eq .Values.environment "prod" }}
  replicas: {{ .Values.replicaCount }}
  {{- else }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    {{/*  function <arg1> <arg2>  with PIPE => result is passed to second fnction as arg  */}}
    matchLabels:
      app: {{ replace " " "-" .Chart.Name | lower  }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name}} #same as matchLabels.app
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.image.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort.http }}